import type { TranslationKeys } from '@zxcvbn-ts/core/dist/types'

export const ltTranslations: TranslationKeys = {
  warnings: {
    straightRow: 'straightRow',
    keyPattern: 'keyPattern',
    simpleRepeat: 'simpleRepeat',
    extendedRepeat: 'extendedRepeat',
    sequences: 'sequences',
    recentYears: 'recentYears',
    dates: 'dates',
    topTen: 'topTen',
    topHundred: 'topHundred',
    common: 'common',
    similarToCommon: 'similarToCommon',
    wordByItself: 'wordByItself',
    namesByThemselves: 'namesByThemselves',
    commonNames: 'commonNames',
    userInputs: 'userInputs',
    pwned: 'pwned',
  },
  suggestions: {
    l33t: 'l33t',
    reverseWords: 'reverseWords',
    allUppercase: 'allUppercase',
    capitalization: 'capitalization',
    dates: 'dates',
    recentYears: 'recentYears',
    associatedYears: 'associatedYears',
    sequences: 'sequences',
    repeated: 'repeated',
    longerKeyboardPattern: 'longerKeyboardPattern',
    anotherWord: 'anotherWord',
    useWords: 'useWords',
    noNeed: 'noNeed',
    pwned: 'pwned',
  },
  timeEstimation: {
    ltSecond: 'mažiau nei sekundę',
    second: 'sekundę',
    seconds: 'sekundes',
    minute: 'minutę',
    minutes: 'minutes',
    hour: 'valandą',
    hours: 'valandas',
    day: 'dieną',
    days: 'dienas',
    month: 'mėnesį',
    months: 'mėnesius',
    year: 'metus',
    years: 'kelis metus',
    centuries: 'dešimtmečius',
  },
//   timeEstimates: {
//     ltSecond: "sekundė",
//     ltSeconds: "sekundės",
//     ltMinute: "minutė",
//     ltMinutes: "minutės",
//     ltHour: "valanda",
//     ltHours: "valandos",
//     ltDay: "diena",
//     ltDays: "dienos",
//     ltYear: "metai",
//     ltYears: "metai",
//     centuries: "amžiai",
//   },
}
